START_WAVELENGTH = 400
END_WAVELENGTH = 600
FEATURES_DIR = "features/"
SUB_TASK_TRAIN = "train"
SUB_TASK_TEST = "test"
TARGET_MAP = {'THF': 0, 'EMK': 1, 'BENZ': 2, 'BENZALD': 3, 'TOL': 4, 'XYL': 5, 'CTCL': 6}
